language: node_js
node_js:
  - "14"

dist: bionic
addons:
  chrome: stable
  sonarcloud:
    organization: ita-social-projects
    project-key: ita-social-projects-green-city-client

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:

  include:
    - stage: build
      script:
      - ng lint
      name: check app by linter
    -
      script:
      - npm run stylelint
      name: check styles by linter
    -
      script:
      - sonar-scanner -Dsonar.sources=. \
                      -Dsonar.host.url=https://sonarcloud.io
      name: check by sonarcloud
    -
      script:
      - ng test --watch=false --progress=false --browsers=ChromeHeadless
      name: test app
    -
      script:
      - ng e2e --protractor-config=e2e/protractor-ci.conf.js
      name: test e2e
    -
      script:      
      -  ng build --prod --delete-output-path --base-href=/GreenCityClient/ --outputPath=dist_aot && rm -rf dist_aot
      name: build app using aot compilation
    - stage: deploy
      script: ng build --prod --base-href=/GreenCityClient/ --aot=false --build-optimizer=false
      name: deploy on gh_pages
      if: branch IN (dev, master)
      deploy:
        provider: pages
        github_token: $TRAVIS_GH_TOKEN
        skip_cleanup: true
        local_dir: dist/GreenCityClient
        on:
          branch: dev
   
